### ISSUE TITLE
Uncaught, unspecified "error" event

### ISSUE THREAD

**Issue by robsyme** [bionode/bionode-ncbi#13]
I'm running a script that starts:

```bash
#!/bin/bash -ue
bionode-ncbi download assembly GCA_000320565.2 > /dev/null
bionode-ncbi download gff GCA_000320565.2 > /dev/null
```

which exits with exitcode 8:

```
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at EventEmitter.emit (events.js:74:15)
    at Duplexify._destroy (/usr/local/lib/node_modules/bionode-ncbi/node_modules/pumpify/node_modules/duplexify/index.js:183:15)
    at /usr/local/lib/node_modules/bionode-ncbi/node_modules/pumpify/node_modules/duplexify/index.js:174:10
    at process._tickCallback (node.js:415:13)
```

Using:
- `bionode-ncbi@1.5.0`
- `pumpify@1.3.3`

Is there a good way to debug this error?

**Comment by robsyme** [comment]
The same scripts are running without issue. I'm chalking this up to network flakiness.
