### ISSUE TITLE
TypeError: Cannot create property 'Run' on string '                                                                '

### ISSUE THREAD

**Issue by esteinig** [bionode/bionode-ncbi#42]
I am running into the following error when searching the SRA for all *Staphylococcus aureus* sequences:

```
Command executed:

 bionode-ncbi search sra "Staphylococcus aureus" > results.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  events.js:165
        throw er; // Unhandled 'error' event
        ^

  TypeError: Cannot create property 'Run' on string '                                                                '
      at /home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/nested-property/index.js:54:27
      at Array.reduce (<anonymous>)
      at Object.setNestedProperty [as set] (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/nested-property/index.js:53:26)
      at Transform.cb [as _transform] (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/lib/tool-stream.js:136:49)
      at Transform._read (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at Transform._write (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_transform.js:172:12)
      at doWrite (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_writable.js:237:10)
      at writeOrBuffer (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_writable.js:227:5)
      at Transform.Writable.write (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_writable.js:194:11)
      at Pumpify.Duplexify._write (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/duplexify/index.js:214:22)
  Emitted 'error' event at:
      at Parser.exports.Parser.Parser.parseString (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/xml2js/lib/parser.js:326:16)
      at /home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/xml2js/lib/parser.js:5:59
      at parseXMLString (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/lib/tool-stream.js:399:5)
      at parseXMLProperty (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/lib/tool-stream.js:386:7)
      at /home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/node_modules/async/lib/async.js:122:13
      at _each (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/node_modules/async/lib/async.js:46:13)
      at Object.async.each (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/node_modules/async/lib/async.js:121:9)
      at Transform.parser [as _transform] (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/lib/tool-stream.js:379:11)
      at Transform._read (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at Transform._write (/home/esteinig/miniconda3/envs/nextflow/lib/node_modules/bionode-ncbi/node_modules/tool-stream/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  .command.stub: line 98: 106508 Terminated              nxf_trace "$pid" .command.trace
```

**Comment by esteinig** [comment]
Recreate without searching for all sequences:

`bionode-ncbi search sra PRJEB2478`
