### ISSUE TITLE
command-line argument parsing error

### ISSUE THREAD

**Issue by Blahah** [bionode/bionode-ncbi#6]
```bash
$ bionode-ncbi help
/Users/rds45/.nvm/v0.10.24/lib/node_modules/bionode-ncbi/cli.js:44
var ncbiStream = options ? ncbi[command](options) : ncbi[command](arg1, arg2,
                                        ^
TypeError: Property 'undefined' of object #<Object> is not a function
    at Object.<anonymous> (/Users/rds45/.nvm/v0.10.24/lib/node_modules/bionode-ncbi/cli.js:44:41)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by bmpvieira** [comment]
Discussion moved to bionode/bionode#25.
